version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-master
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres